### ISSUE TITLE
Sums of complex matrices throw gradient error

### ISSUE THREAD

**Issue by QCmonk** [cvxgrp/dccp#67]
Great tool but I believe there is a bug when working with complex scalar sums. When running the following minimal working example with cvxpy 1.0.3 and python 3.6.10:

```
import dccp
import cvxpy as cp
import numpy as np

a = cp.Variable(1)
b = cp.Variable(1)
W = a* np.eye(2)+1j* b* np.eye(2)
prob = cp.Problem(cp.Maximize(cp.norm(W)), [W>>0, cp.trace(W)==1])
prob.solve(method='dccp')
```

An error is thrown about casting rules deep in the core of cvxpy. This will not occur if instead a single complex variable is defined for an equivalent definition of W. It seems to me that something erroneous is occuring when considering sums of variables with different types are being performed. A fix to this woud be very much appreciated as I think the problem is a bit too deep in the source code for me to fix myself. 

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    prob.solve(method='dccp')
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\problems\problem.py", line 395, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\problem.py", line 55, in dccp
    self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\problem.py", line 222, in iter_dccp
    convexified_obj = convexify_obj(self.objective)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\objective.py", line 46, in convexify_obj
    lin = linearize(obj.expr)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\linearize.py", line 58, in linearize
    grad_map = expr.grad
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\atom.py", line 399, in grad
    grad_arg = arg.grad
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\atom.py", line 399, in grad
    grad_arg = arg.grad
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\atom.py", line 399, in grad
    grad_arg = arg.grad
  [Previous line repeated 1 more time]
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\atom.py", line 393, in grad
    grad_self = self._grad(arg_values)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\affine\binary_operators.py", line 179, in _grad
    return super(MulExpression, self)._grad(values)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\atoms\affine\affine_atom.py", line 137, in _grad
    self.size,
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 327, in get_problem_matrix
    build_lin_op_tree(lin, linPy_to_linC)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 518, in build_lin_op_tree
    make_linC_from_linPy(linPy, linPy_to_linC)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 492, in make_linC_from_linPy
    set_linC_data(linC, linPy)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 466, in set_linC_data
    set_matrix_data(linC, linPy)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 438, in set_matrix_data
    linC.set_dense_data(format_matrix(linPy.data, shape=linPy.shape))
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 200, in set_dense_data
    return _cvxcore.LinOp_set_dense_data(self, matrix)
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'

**Comment by xinyueshen** [comment]
Hi @QCmonk, the error comes from taking gradient of `1j * b` in cvxpy, and we'll look into it. Meanwhile, for the example in your code, a quick work-around is as follows.
```
a = cp.Variable(1)
b = cp.Variable(1, complex=True)
W = a* np.eye(2) + b* np.eye(2)
prob = cp.Problem(cp.Maximize(cp.norm(W)), [W >> 0, cp.trace(W) == 1, np.real(b) == 0])
prob.solve(method='dccp')
```

**Comment by QCmonk** [comment]
Hi @xinyueshen, thank you for the speedy reply. Unfortuantely this work-around does not work for me with the following traceback:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    prob.solve(method='dccp')
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\cvxpy\problems\problem.py", line 395, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\problem.py", line 41, in dccp
    if not is_dccp(self):
  File "C:\Users\Joshua\Anaconda3\envs\convexpy\lib\site-packages\dccp\problem.py", line 175, in is_dccp
    for arg in constr.args:
AttributeError: 'bool' object has no attribute 'args'

**Comment by xinyueshen** [comment]
Hi @QCmonk, just noticed that you used cvxpy 1.0.3. Now dccp works with cvxpy 1.1.1, so you could update cvxpy and then have a try.

**Comment by QCmonk** [comment]
Hi @xinyueshen, that was actually a typo my apologies - I have dccp 1.0.3 and cvxpy 1.1.1. Fresh install of both cvxpy and dccp gives the same error as above.

**Comment by xinyueshen** [comment]
Oops sorry the last constraint should be `cp.real(b) == 0`, not `np.real(b) == 0`.

**Comment by QCmonk** [comment]
Ah of course, my apologies I should have seen that. Unfortuantely while this is a workaround for the example above it does not work for my actual use case which is more along the lines of the following code block.

`
import dccp
import numpy as np
import cvxpy as cp

x = cp.Variable(1)
W = x * A

prob = cp.Problem(cp.Maximize(cp.norm(W)), [W >> 0, cp.trace(W) == 1])
prob.solve(method='dccp')
`
where A is a complex matrix. Defining x as a complex variable with the imaginary component constrained to zero does not appear to work as it does for the previous example. It seems there should be a way to use your trick here but I cannot seem to avoid the type casting error. Are you able to see a similar fix here?

**Comment by xinyueshen** [comment]
Hi @QCmonk, you could try the following.
```
A = np.eye(2) + 1j * np.eye(2) # A is a given complex matrix
A_real = np.real(A)
A_imag = np.imag(A)

x_real = cp.Variable(1, complex=False)
x_imag = cp.Variable(1, complex=True)
W = x_real * A_real + x_imag * A_imag  

prob = cp.Problem(cp.Maximize(cp.norm(W)), [W>>0,  cp.trace(W) == 1,  cp.real(x_imag) == 0])
prob.solve(method='dccp')
print(prob.status, x_real.value, x_imag.value)
```

**Comment by QCmonk** [comment]
Ah I think that gets me close enough, though some minor changes are needed to make it equivalent to the original formulation

```
A = np.eye(2)+ 1j*np.asarray([[0,1],[1,0]])
A_real = np.real(A)
A_imag = np.imag(A)

x_real = cp.Variable(1, complex=False)
x_imag = cp.Variable(1, complex=True)

W = x_real*A_real + x_imag*A_imag

prob = cp.Problem(cp.Maximize(cp.norm(W)), [W>>0, cp.trace(W)==1.0, cp.real(x_imag)==0, cp.imag(x_imag)==x_real])
prob.solve(method='dccp')

print(prob.status, x_real.value, x_imag.value)
```


Thank you very much for the help! Hopefully the bugfix will come along soon as well.
