### ISSUE TITLE
DCCP problem crashes with attribute error

### ISSUE THREAD

**Issue by gioperin** [cvxgrp/dccp#51]
Hi maintainers!

Actually, I have more than one problem/doubt. I'm going to explain what I'm doing and provide a minimal example.
I have a problem in the form `x.T@P@x + q1.T@x + log(1+q2.T@x)`, which is the sum of a quadratic program with a strictly concave function, hence, a difference of convex functions.
 First of all, I have this minimal example:
```
import dccp
import cvxpy as cp
import osqp
import numpy as np
import mosek

x = cp.Variable(5)
t = cp.Variable(1)
P = 16*np.diag(np.random.rand(5))
q = 7*np.random.rand(5).reshape((5,1))
qlog = 24*np.random.rand(5).reshape((5,1))
objective = cp.quad_form(x,P) + q.T@x - t
A = 2*np.random.rand(5,5)
b = np.random.rand(5)
constraints = [A@x==b, -cp.log(1+qlog.T@x)==t]
problem = cp.Problem(cp.Minimize(objective), constraints)
print(problem.is_dcp())
print(dccp.is_dccp(problem))
problem.solve(verbose=True, solver='SCS', method='dccp')
```
What happens is that OSQP, ECOS and GUROBI don't even start the optimization because the problem cannot be reduced to a QP and a conic solver is needed. I thought the reason why dccp exists is to transform that problem in a convex one linearizing the concave part at every iteration, so any quadratic solver should do it. Anyway, SCS and MOSEK work. But soon, an exception is thrown:

AttributeError: 'AddExpression' object has no attribute '_lazy_canonical_form' (cvxpy\utilities\performance_utils.py)
During handling of the above exception, another exception occurred:
AttributeError: 'real' object has no attribute '_lazy_canonical_form' (cvxpy\utilities\performance_utils.py)
During handling of the above exception, another exception occurred: 
TypeError: cannot unpack non-iterable NotImplementedType object (cvxpy\atoms\atom.py)

I thought there were problems of versions, that maybe the attribute _laxy_canonical_form existed in a previous version of cvxpy. But I found no trace of it. However, I reinstalled Anaconda and now everything is up to date. The problem persists.
Moreover, this is a minimal example that I did to debug my code. In my problem I have matrix P and vectors q1 and q2 built so that dccp tells me that the problem is not dccp. Given that, with only the QP, the problem is correctly solved by OSQP,  is it possible that it depends on the value of P and q?
Finally, is the way shown the correct one to define a dccp problem, with the auxiliary variable t?

Thanks in advance,

Giovanni

**EDIT**: I was doing a bad mistake building my matrix P. After debugging, now I have the same attribute error and type error as the minimal working example. However, what was said was true the same. Dccp told me that the problem was not dccp and it was strange, because OSQP solved the convex part.

**Comment by xinyueshen** [comment]
Hi @gioperin, a few things are fixed, but to get the updated dccp package you'll need to clone this repo or download the zip and run setup.py therein. Another thing to notice is that dccp now works with cvxpy>=1.0, but not with cvxpy>=1.1, so you'll need to downgrade your cvxpy version (e.g. to 1.0.21) and use `*` for matrix-vector multiplication.

To get the example work, `A`, `b`, and `qlog` should be chosen such that the domain of log  `1+qlog.T@x>=0` is feasible with `A*x==b`. And the solver parameter `tau` needs to be set manually by `problem.solve(method='dccp', tau=1.5)`.

**Comment by gioperin** [comment]
Thank you @xinyueshen, I appreciate your help.
Now the problem seems to be solved, however, on pip, the version of DCCP is 1.0.2 whereas cloning the repo, I got 1.0.0. The problem was solved, anyway. Nonetheless, I still see that the only solvers working are SCS and MOSEK and, unluckily, they are the only ones having serious problems in handling constraints with upper bounds set to `inf`. They interpret them as `nan` and fail to converge. This behavior is solver specific and the form of the constraint should be handled accordingly by CVXPY, not by me. Indeed, if I solve the quadratic program without the log with any other solver, I get a result. MOSEK and SCS, on the other hand, fail because they have `nan` upper bounds, but they are the only ones I can use for the DC program!

**Comment by SteveDiamond** [comment]
@gioperin setting the bounds to inf is not officially supported by cvxpy. Did it say otherwise in the docs?

**Comment by xinyueshen** [comment]
@gioperin You could rewrite the problem as
`objective = cp.quad_form(x,P) + q.T*x + t`
`constraints = [A*x==b, 1+qlog.T*x==cp.exp(t)]
`
Then other solvers such as ECOS should work for dccp as well.

**Comment by gioperin** [comment]
@SteveDiamond the problem was that I am used to express a bound for every constraint. Of course, with CVXPY, I can simply avoid to put it, if it is inf. However, expressing all the constraints may be useful and I tell you why: I may want to investigate what happens if I let my variables be unbounded or bounded and if CVXPY accepted also inf as bound, this would be easier to do, with the same code and just changing the input of my program. Of course there are workarounds for this, but I think that handling inf constraints would be useful for CVXPY. Note that I'm not saying that you should change the behavior so that the users must express the constraint. Just let them choose how to write their code. Moreover, given that you are talking about CVXPY's docs, maybe it is just a problem of mine, but I find it really difficult to understand anything from there.

@xinyueshen thanks for your suggestion, I should have thought about it. However, ECOS only works for the trivial example but fails for my bigger problem. I will go for MOSEK avoiding inf constraints.
