### ISSUE TITLE
The programs in Example File can't work.

### ISSUE THREAD

**Issue by RobertGCNiu** [cvxgrp/dccp#36]
There are some bugs when I run the example codes. At first, I guess the program is designed under CVXPY 0.4.11 version. But the new bugs will incur after I reinstall the CVXPY 0.4.11. It said, "'LeqConstraint' object has no attribute 'expr'". 
Then I install the CVXPY 1.0.19 by Anaconda2 and Anaconda3 . However, none of them can work. For example, all of the codes said "Variable name % must be a string". Can you please tell me how to run the program properly?

**Comment by xinyueshen** [comment]
Hello @RobertGCNiu, the example codes are currently under update. Right now the examples `test.py`, `filter_design.py`, and `trajectory_control_obstacle.py` are able to work with CVXPY 1.0.10 by Anaconda 2.

**Comment by xinyueshen** [comment]
Hello @RobertGCNiu, sorry that the example codes are currently under update. Right now the examples `test.py`, `filter_design.py`, and `trajectory_control_obstacle.py` can work with CVXPY 1.0.10 by Anaconda2.

**Comment by SteveDiamond** [comment]
I'll do a pass and update the examples.

**Comment by xinyueshen** [comment]
@SteveDiamond Thanks! But I'm also updating them, and just in case of any conflict I'm working on `circle_packing` and `path_avio_control` now.

**Comment by SteveDiamond** [comment]
Oops sorry! I'll stop.

**Comment by RobertGCNiu** [comment]
Thanks for your response! But I found that only filter_design.py and test.py can work well so far.

**Comment by RobertGCNiu** [comment]
I just checked the program codes in the example file. Except for the circle_packing.py and path_avoi_control.py, the codes can work well.

**Comment by RobertGCNiu** [comment]
I noted you have just updated your codes in the Example file and I checked the codes one by one. It seems the bugs come from the update of function in CVXPY. path_avio_control.py, sparse_eigen.py, sparse_recovery_plot.py and sparse_singular.py  can work well now.

**Comment by xinyueshen** [comment]
Still working on the update and fixing bugs. Will let you know when it is finished. Thanks @RobertGCNiu .

**Comment by RobertGCNiu** [comment]
Many thanks!

**Comment by xinyueshen** [comment]
@RobertGCNiu The example codes are all updated. Please let me know if you still get errors.

**Comment by RobertGCNiu** [comment]
There are still some errors for circle_packing.py...    @xinyueshen  
![图片](https://user-images.githubusercontent.com/16495354/54068138-13fd6280-4284-11e9-97e9-c2a1271b9914.png)

**Comment by RobertGCNiu** [comment]
The cvxpy 1.0.21 and dccp are installed by Anaconda2.

**Comment by xinyueshen** [comment]
Hi @RobertGCNiu, I've tested it with cvxpy 1.0.21, and it works (maybe need to change different solvers sometimes such as 'ECOS' and 'SCS'). Did you install DCCP also by Anaconda2? If so, you are not running the updated DCCP code. To use the updated code, you need to directly clone this repository and run (for example) circle_packing.py therein (or run `python setup.py` to install).

**Comment by RobertGCNiu** [comment]
Hello @xinyueshen , it can work well! Thanks! I just cloned the repository and run `python setup.py install`.

**Comment by malayandi** [comment]
I have installed DCCP from source (with `python setup.py install`) and am using cvxpy 1.0.21. I am trying to run path_avoi_control.py but running into the following error:

```
Traceback (most recent call last):
  File "path_avoi_control.py", line 60, in <module>
    prob.solve(method='dccp', ep = 1e-1)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/dccp-1.0.0-py3.6.egg/dccp/problem.py", line 42, in dccp
    result_temp = iter_dccp(self, max_iter, tau, mu, tau_max, solver, ep, max_slack, **kwargs)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/dccp-1.0.0-py3.6.egg/dccp/problem.py", line 225, in iter_dccp
    logger.info("iteration=%d, cost value=%.5f, tau=%.5f", it, prob_new.solve(**kwargs), tau)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 496, in _solve
    self._solving_chain.apply(self._intermediate_problem)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/reductions/matrix_stuffing.py", line 79, in apply
    Afull, bfull = extractor.affine(expr_list)
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 77, in affine
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 77, in <listcomp>
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 233, in canonicalize
    obj, constr = arg.canonical_form
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/anaconda3/envs/cvx/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 240, in canonicalize
    data)
TypeError: 'NotImplementedType' object is not iterable
```

Any suggestions?

**Comment by malayandi** [comment]
What version of Python are you using? I am on 3.6

**Comment by RobertGCNiu** [comment]
Python 2.7.13

------------------
Best Regards,


        G.C  Niu


 




------------------ 原始邮件 ------------------
发件人: "Andy Palan"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 上午9:11
收件人: "cvxgrp/dccp"<dccp@noreply.github.com>;
抄送: "Kelvin"<714984847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cvxgrp/dccp] The programs in Example File can't work. (#36)




What version of Python are you using? I am on 3.6

**Comment by malayandi** [comment]
I have installed Python 2.7.13, cvxpy 1.0.21, and DCCP from source but am still having the same issue as above. Any ideas?

**Comment by RobertGCNiu** [comment]
It works well on my computer. Please check your CVXPY with example in https://www.cvxpy.org/

**Comment by xinyueshen** [comment]
Hi @malayandi , could you show the error message you got using Python 2.7.13? (Is it the same as the one you posted with Python 3.6?)

**Comment by malayandi** [comment]
Hi Xinyue, yes, same error as the one I posted with Python 3.6.

**Comment by malayandi** [comment]
@RobertGCNiu I tried testing my cvxpy installation with nosetests and got two failures:

```
....................................................F....F..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.......S.............................................................................................................................................................................................................................................................................
======================================================================
FAIL: Test eigenvalue atoms.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/envs/cvx27/lib/python2.7/site-packages/cvxpy/tests/test_complex.py", line 319, in test_eigval_atoms
    self.assertAlmostEqual(result, value, places=3)
  File "/anaconda3/envs/cvx27/lib/python2.7/site-packages/cvxpy/tests/base_test.py", line 38, in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places)
AssertionError: 102.1958771895555 != 102.19999999999995 within 3 places
-------------------- >> begin captured stdout << ---------------------
----------------------------------------------------------------------------
	SCS v1.2.6 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 201, CG tol ~ 1/iter^(2.00)
eps = 1.00e-08, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 40, constraints m = 96
Cones:	primal zero / dual free vars: 54
	sd vars: 42, sd blks: 2
Setup time: 3.05e-04s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 3.37e+00  2.90e+00  9.99e-01 -1.64e+02  6.50e+02  0.00e+00  3.33e-04 
   100| 1.79e-03  3.04e-04  2.71e-04  1.02e+02  1.02e+02  5.06e-14  2.40e-03 
   200| 4.68e-06  2.14e-07  1.35e-07  1.02e+02  1.02e+02  1.69e-14  3.92e-03 
   300| 1.56e-06  2.49e-08  5.46e-09  1.02e+02  1.02e+02  5.06e-14  5.26e-03 
   400| 5.19e-07  7.91e-09  2.15e-09  1.02e+02  1.02e+02  5.06e-14  6.59e-03 
   500| 5.79e-03  2.13e-03  4.13e-03  1.02e+02  1.03e+02  1.72e-14  8.21e-03 
   600| 6.19e-04  2.47e-06  8.72e-08  1.02e+02  1.02e+02  1.73e-14  9.89e-03 
   700| 2.07e-04  7.92e-07  7.69e-10  1.02e+02  1.02e+02  1.73e-14  1.16e-02 
   800| 6.90e-05  2.90e-07  1.02e-08  1.02e+02  1.02e+02  1.73e-14  1.31e-02 
   900| 2.30e-05  1.80e-07  1.41e-08  1.02e+02  1.02e+02  1.73e-14  1.45e-02 
  1000| 7.68e-06  5.99e-08  8.71e-09  1.02e+02  1.02e+02  1.73e-14  1.61e-02 
  1100| 2.56e-06  4.09e-08  1.78e-09  1.02e+02  1.02e+02  1.73e-14  1.81e-02 
  1200| 8.51e-07  1.41e-08  1.08e-09  1.02e+02  1.02e+02  1.73e-14  1.96e-02 
  1300| 1.55e-01  5.14e-02  2.17e-02  1.11e+02  1.06e+02  1.93e-14  2.12e-02 
  1400| 8.30e-04  3.97e-06  1.69e-07  1.02e+02  1.02e+02  1.78e-14  2.31e-02 
  1500| 2.79e-04  1.06e-06  2.33e-08  1.02e+02  1.02e+02  1.78e-14  2.47e-02 
  1600| 9.30e-05  3.51e-07  1.97e-09  1.02e+02  1.02e+02  1.78e-14  2.63e-02 
  1700| 3.10e-05  1.19e-07  8.15e-09  1.02e+02  1.02e+02  1.78e-14  2.78e-02 
  1800| 1.03e-05  5.53e-08  5.59e-10  1.02e+02  1.02e+02  1.78e-14  2.94e-02 
  1900| 3.43e-06  2.92e-08  1.11e-08  1.02e+02  1.02e+02  1.78e-14  3.11e-02 
  2000| 1.14e-06  1.59e-08  9.06e-09  1.02e+02  1.02e+02  1.78e-14  3.25e-02 
  2100| 3.82e-07  6.56e-09  7.90e-10  1.02e+02  1.02e+02  1.78e-14  3.38e-02 
  2200| 1.27e-07  1.77e-09  2.44e-10  1.02e+02  1.02e+02  1.78e-14  3.52e-02 
  2300| 4.24e-08  1.24e-09  3.00e-11  1.02e+02  1.02e+02  1.78e-14  3.65e-02 
  2400| 6.19e-03  3.20e-04  4.37e-05  1.02e+02  1.02e+02  1.81e-14  3.81e-02 
  2500| 6.13e-04  2.44e-06  1.06e-07  1.02e+02  1.02e+02  1.82e-14  3.99e-02 
----------------------------------------------------------------------------
Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate
Timing: Solve time: 3.99e-02s
	Lin-sys: avg # CG iterations: 2.61, avg solve time: 2.29e-06s
	Cones: avg projection time: 1.23e-05s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.1363e-08, dist(y, K*) = 2.0599e-09, s'y/|s||y| = 1.1225e-10
|Ax + s - b|_2 / (1 + |b|_2) = 6.1255e-04
|A'y + c|_2 / (1 + |c|_2) = 2.4374e-06
|c'x + b'y| / (1 + |c'x| + |b'y|) = 1.0632e-07
----------------------------------------------------------------------------
c'x = 102.1959, -b'y = 102.1959
============================================================================

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test matrix norms.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/envs/cvx27/lib/python2.7/site-packages/cvxpy/tests/test_complex.py", line 280, in test_matrix_norms
    self.assertAlmostEqual(result, sigma_max, places=3)
  File "/anaconda3/envs/cvx27/lib/python2.7/site-packages/cvxpy/tests/base_test.py", line 38, in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places)
AssertionError: 26.237780158787803 != 26.23696793293335 within 3 places

----------------------------------------------------------------------
Ran 1882 tests in 14.330s

FAILED (SKIP=2, failures=2)
```

But these failures are only small numerical issues, and do not seem to be something that would cause the issue I'm facing above with dccp.

**Comment by malayandi** [comment]
I tried every example file provided; `ML_cov_est.py` and `sparse_recovery.py` work for me but for all the rest, I get the same error as above.

**Comment by malayandi** [comment]
Figured it out -- the issue was caused by using cvx.real(...) in line 77 of constraint.py. That function did not have a graph implementation, which caused the issue. Once I commented it out, all the examples work.

**Comment by RobertGCNiu** [comment]
It's good to hear that.

**Comment by Arseniy82** [comment]
I have the same "Variable X must be a string" issue. I have tried various constructors but I can't even create a variable:


ncvx.Card(3,2,1)
Traceback (most recent call last):
  File "<ipython-input-4-6980d6dd46fe>", line 1, in <module>
    ncvx.Card(3,2,1)
  File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\ncvx\card.py", line 33, in __init__
    super(Card, self).__init__(rows, 1, *args, **kwargs)

  File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\ncvx\noncvx_variable.py", line 29, in __init__
    super(NonCvxVariable, self).__init__(*args, **kwargs)

  File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\expressions\variable.py", line 75, in __init__
    raise TypeError("Variable name %s must be a string." % name)

TypeError: Variable name 1 must be a string.


Same thing repeats with all example files I tried to run. I am on Python 3.6.9 (Anaconda 1.9.7)
cvxpy 1.0.21, ncvx 0.1.8

CVX package on itself works perfectly fine bythe way. Do you have any suggestions on how to get it to work?
